### ISSUE TITLE
Stuck when downloading from http://dl.yf.io/dla/models

### ISSUE THREAD

**Issue by zijianh4** [Xianpeng919/MonoCon#14]
Hi,
Thanks for your great work. Currently, I am trying to train a model by myself, and it seems that the link http://dl.yf.io/dla/models is down. Do you have a local copy of the http://dl.yf.io/dla/models/imagenet/dla34-ba72cf86.pth model, or what I can only do is to wait the link works again? Thanks!

**Comment by zqdhnb** [comment]
@zijianh4 Hi,
May I ask how do you solve this problem?

**Comment by zijianh4** [comment]
> 

Hi, the server will resume after some time but I am not sure how long it will be. Previously, I just waited for one or two more days and the model can be downloaded.
