### ISSUE TITLE
Can't get correct visualize results by args: "--show"

### ISSUE THREAD

**Issue by BokyLiu** [Xianpeng919/MonoCon#19]
I think this command `tools/test.py configs/monocon/monocon_dla34_inference_200e_kitti.py ../monocon_val_ckpt.pth --eval bbox --show-dir show --show` could not visualize the monocon's result. 
Did anyone know how to visualize detect results?

**Comment by BokyLiu** [comment]
Got it, implement function `show_results` ,  refer to implemention in SingleStageMono3DDetector

**Comment by chenyonx** [comment]
so,how to solve zhe problem?
