### ISSUE TITLE
how to test in internet videos?

### ISSUE THREAD

**Issue by lucasjinreal** [Xianpeng919/MonoCon#2]
how to test in internet videos? is that possible with kitti pertained weights?

**Comment by Xianpeng919** [comment]
Our method needs camera intrinsics to calculate the 3D box's localization parameters during inference. I didn't try to test internet videos before. If you have the video's camera intrinsics, it might be possible to do monocular 3D object detection frame by frame.

**Comment by lucasjinreal** [comment]
@Xianpeng919 Does the extrinsic matters?

**Comment by Xianpeng919** [comment]
The extrinsic should matter because our method is trained based on the KITTI dataset (training split), which only includes about 3k images for training.
