### ISSUE TITLE
clean version of MonoDLE and framework dependency

### ISSUE THREAD

**Issue by excitohe** [Xianpeng919/MonoCon#4]
Hi, thx for your excellent work! Two common questions here:
1. Do you provide a clean version of your unofficial MonoDLE reimplementation? Or can you provide it recently for fast and fair comparision in mmdet3d?
2. Is your implementation independent of mmdet and mmseg? Can I port the contents of the MonoCon folder directly to mmdet3d master version? Or do you have potential modifications in mmdet?
Thx again~  ^_^

**Comment by Xianpeng919** [comment]
Thank you for your interest in our work. We will provide a clean version of my unofficial MonoDLE recently. Our current code is not compatible with the master branch of mmdet3d. We will update our code and make it compatible with the mmdet3d's master branch in the future.

**Comment by excitohe** [comment]
Thank you for your reply, looking forward to the MonoDLE baseline, and the merge version to the mmdet3d master.
Here is a simple question, in your kitti_converter_monocon, it generates both `bbox_cam3d` and `bbox_cam3d_cam0`, however, in kitti_mono_dataset_monocon.py, it still use the origin `bbox_cam3d`. I think the generated `bbox_cam3d_cam0` vars is the correct regression target, so why generate but not use it? 
^_^

**Comment by Xianpeng919** [comment]
This is because we learn the projected 3D centers in our algorithm. We use center2d instead of the x and y coordinate in bbox_cam3d. I stored the bbox_cam3d_cam0 just for convenience.

**Comment by excitohe** [comment]
Hi, I migrate your monocon folder into mmdet3d master, then do some little modifications:
1. rename some heads and losses. 
2. use DLANet in mmdet3d master and DLAUP neck in your version, (DLANet(master) and DLA(yours) backbone maybe same, DLAUp(yours) and DLANeck(master) is different (no last IDAUpsample)).
3. Train with 4GPUs.
Here is my training result:
```
Car AP40@0.70, 0.70, 0.70:
3d   AP40:21.2635, 16.1056, 13.4211
```
Here is my training log:
https://paste.ubuntu.com/p/CtJH9Hk52F/
Any advise for improve my training performance? Or multi-GPU gets similar low performance in your exps. Thx! @Xianpeng919 
^_^

**Comment by Xianpeng919** [comment]
I think you need to change the learning rate accordingly when using more GPUs for training.

**Comment by excitohe** [comment]
Thx for your advise, I will try again.

**Comment by Senwang98** [comment]
@Xianpeng919 
Will you update MonoDLE version MonoCon in future.
I fail to reproduct your monocon based on MonoDLE's code.
I think I only to modify kitti.py, model.py and loss.py in monodle.
