### ISSUE TITLE
About performance on personal data

### ISSUE THREAD

**Issue by wu-hrww** [Xianpeng919/MonoCon#6]
Hello, @Xianpeng919 , I really appreciate your awesome work. I plan to deploy your work on real-vehicle platforms for vehicle tracking, but test performance on my personal data is very strange. All 3D boxes are of low scores. With a threshold of `0.1`, nearly no box would be outputted. Several examples are shown as follows：
![result_1](https://user-images.githubusercontent.com/64794281/165889294-96ba3456-c91b-488f-a7e9-299207eac241.jpg)
![result_2](https://user-images.githubusercontent.com/64794281/165889302-ee947f95-432b-417d-a5c8-ba344aa2f48c.jpg)
![result_3](https://user-images.githubusercontent.com/64794281/165889361-cb2d0437-3b53-4620-b261-d97441e4b35c.jpg)
And the camera intrinsics matrix is `[[1201.8,-0.935,953.9414],[0.000000,1211.80,636.9038],[0.000000,0.000000,1.000000]]`.
The raw images are attached below. Looking forward to your help.
[my_data.zip](https://github.com/Xianpeng919/MonoCon/files/8588340/my_data.zip)

**Comment by Xingyi0220** [comment]
I think that they are not rectified photos

**Comment by Xingyi0220** [comment]
Personally thinking, you should rectify the photos and apply the rectified projection matrix
